apiVersion: apps/v1 # Deployment per l'app edge
kind: Deployment 
metadata:
  name: edge-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-app
  template:
    metadata:
      labels:
        app: edge-app
    spec:
      containers:
        - name: edge-app
          image: edge-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          resources:           
            requests:
              cpu: "100m"      # Minimo 0.1 CPU
              memory: "128Mi"  # Minimo 128MB di memoria
            limits:
              cpu: "1000m"      # Massimo 1 CPU 
              memory: "512Mi"  # Tetto massimo di memoria 
---
apiVersion: v1
kind: Service
metadata:
  name: edge-app-service
spec:
  selector:
    app: edge-app
  type: NodePort
  ports:
    - port: 80 # Porta del servizio
      targetPort: 5000 # Porta del container
      nodePort: 30080 # Porta esposta sul nodo

