apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-app
  template:
    metadata:
      labels:
        app: edge-app
    spec:
      containers:
        - name: edge-app
          image: edge-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: edge-app-service
spec:
  selector:
    app: edge-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080
